service: event-booking-app
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    EVENTS_TABLE: Events
    BOOKINGS_TABLE: Registrations
    USER_TABLE: YourUserTable
    COGNITO_CLIENT_ID: 4v4qbgptde4v367c05hd4gq2rf
    COGNITO_CLIENT_SECRET: kqh481640kr3jq48g05c96sch22jgokaate4r5ommrpoe6atkbc 
    USER_ID_INDEX: userId-index
    SENDER_EMAIL: mudge.andrew@gmail.com   # <-- Added for SES

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: arn:aws:dynamodb:us-east-1:*:table/*
        - Effect: Allow
          Action:
            - cognito-idp:SignUp
            - cognito-idp:AdminConfirmSignUp
            - cognito-idp:InitiateAuth
            - cognito-idp:ConfirmSignUp
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"   # Allow Lambda to send SES emails

functions:
  getEvents:
    handler: aws/lambdas/getEvents.handler
    events:
      - http:
          path: events
          method: get
          cors: true

  bookEvent:
    handler: aws/lambdas/bookEvent.handler
    events:
      - http:
          path: book
          method: post
          cors: true

  getRegistrations:
    handler: aws/lambdas/getRegistrations.handler
    events:
      - http:
          path: registrations
          method: get
          cors: true

  signup:
    handler: aws/lambdas/signup.handler
    events:
      - http:
          path: signup
          method: post
          cors: true

  login:
    handler: aws/lambdas/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  confirmSignup:
    handler: aws/lambdas/confirmSignup.handler
    events:
      - http:
          path: confirm-signup
          method: post
          cors: true

  saveUser:
    handler: aws/lambdas/saveUser.handler
    events:
      - http:
          path: saveUser
          method: post
          cors: true
